language: ruby
rvm: 2.6.3
cache: bundler
services:
- postgresql
- redis-server
env:
  global:
  - DATABASE_URL="postgresql://postgres:@localhost:5432/miq_bot_test?encoding=utf8&pool=5&wait_timeout=5"
before_install:
- sudo pip install yamllint
before_script:
- bundle exec rake db:setup
